name: build-OMQqiskit-exe
on:
  workflow_dispatch:
  push:
    paths: ["omqqiskit.c"]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc -O2 -s omqqiskit.c -o OMQqiskit.exe -lm
      - run: certutil -hashfile OMQqiskit.exe SHA256 > OMQqiskit.exe.sha256
      - uses: actions/upload-artifact@v4
        with:
          name: OMQqiskit
          path: |
            OMQqiskit.exe
            OMQqiskit.exe.sha256

  test-python-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build Shared Library
        run: clang -O2 -fPIC -shared omqqiskit.c -o libomqqiskit.so -lm
      - name: Run Unit Tests
        run: python test_omqqiskit.py
